const browser = require('./index')
browser
  .launchBrowser(true)
  .launchPage('https://youtube.com')
  .click('#thumbnail')
  .fillInput('#search', 'RTGame')
  .press('Enter')
  .delay(2000)
  .close()
  .exit()
